spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB
springdoc:
  default-consumes-media-type: application/json

server:
  port: 8000
  servlet:
    context-path: /api/v1/