spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/campus_overflow
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: localhost
    port: 1025
    username: CampusOverflow
    password: password
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

application:
  security:
    jwt:
      secret-key: QwFBT3u38YUDnyj5/ol0BKvoLTkPRq02z05j5I3dJrg=
      expiration-time: 86400000
  mailing:
    frontend:
      activation-url: http://localhost:8000/activate-account
